### ISSUE TITLE
Добавить автопост на G+

### ISSUE THREAD

**Issue by lemenkov** [RussianFedora/rf-web#28]
Сейчас лично я вообще не понимаю, как работают камменты на сайте, но это ладно. Как бы я хотел бы видеть - пост появляется на сайте, сразу же появляется на G+, и камменты на сайте и на G+ одни и те же.

С объединенными камментами можно пока проигнорировать, но автопост бы надо подключить. Гугли выложили инструкцию того, как это можно сделать:

https://developers.google.com/+/domains/posts/creating

**Comment by temamagic** [comment]
Кто вообще пользуется соц сетью гугл плюс?

**Comment by ignatenkobrain** [comment]
@temamagic все нормальные люди?)

**Comment by temamagic** [comment]
@ignatenkobrain он мертвый) даже в гугле отказались от его дальнейшего навязывания

**Comment by ignatenkobrain** [comment]
вечер прохладных историй от @temamagic

**Comment by lemenkov** [comment]
@temamagic тем не менее, автопост бы туда сделать. И на FB тоже (см. #35).

**Comment by lemenkov** [comment]
Ну, кстати, получается, что @temamagic был прав :)

[...sunsetting consumer Google+](https://www.blog.google/technology/safety-security/expediting-changes-google-plus/).

Так что тикет надо закрывать, как CANTFIX.

**Comment by temamagic** [comment]
еее
